### ISSUE TITLE
Error in main.py

### ISSUE THREAD

**Issue by saaerkk** [shadow7412/fronius-driver#1]
When I try to run it as a docker I get the following error (on a seperate machine on the same network)

Traceback (most recent call last):
  File "/app/main.py", line 45, in <module>
    assert username == 'string:service', username
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Attached the Base64 image
![image](https://github.com/user-attachments/assets/6c90e0b8-e573-4986-b127-73be476ede85)
![image](https://github.com/user-attachments/assets/664ffdd1-6a46-4a7b-9fe0-ebb1ac38c4c5)
How the user selection looks like

**Comment by shadow7412** [comment]
Interesting. What version of the fronius firmware?

**Comment by saaerkk** [comment]
Symo 6.0-3-M with the latest software 3.31.1-5 and fro35220.upd on the inverter

**Comment by shadow7412** [comment]
Try that.

**Comment by saaerkk** [comment]
Now I got past the login screen and got following errors with the latest version:

Traceback (most recent call last):
  File "/app/main.py", line 50, in <module>

    limit = driver.find_element(By.CSS_SELECTOR, '[input-validator="softLimitValidator"]')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [input-validator="softLimitValidator"]; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:187:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:505:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:135:16

![image (1)](https://github.com/user-attachments/assets/271ddcd6-33d4-4e08-8bb0-c16a6c1ccc13)
The SoftLimit is found under http://fronius-ip/#/settings/evu and the settting is adjusted as in the picture below
![image](https://github.com/user-attachments/assets/d8d68809-9e70-402f-b4eb-ef09baeb62b9)

**Comment by shadow7412** [comment]
Hmm. The url you've written matches the one it goes to https://github.com/shadow7412/fronius-driver/blob/6754bbd9656e6c7a6f3fd37a373276d5363b2f0e/main.py#L27

I guess I can try re-navigating there post-login, under the assumption that your version doesn't correctly do that. Just for sanity's sake, would you mind listing all the arguments you're passing (redacting the 2 secret keys of course)

**Comment by saaerkk** [comment]
docker run --rm shadowbert/fronius-driver -t HA-token  -u http://10.11.101.108:8123 -f http://10.11.111.10 -p "password"
The script shows that it gets the value from HA and then continues

**Comment by saaerkk** [comment]
Might it be a time issue? Since when I browse to the site normally, there is a delay (about 5s) before the page is fully loaded and the softlimit is visible from when I have OK'd the login

**Comment by shadow7412** [comment]
Shouldn't be... that's why I have this line which should wait up to 10 seconds

https://github.com/shadow7412/fronius-driver/blob/6754bbd9656e6c7a6f3fd37a373276d5363b2f0e/main.py#L26

It also doesn't really explain why the screenshot is of the general view page.

Anyway, I'm just building a version that will try navigating to the evu page again if it can't find the field. I'll let you know when it's ready.

**Comment by shadow7412** [comment]
Done. Let me know how it goes.

**Comment by saaerkk** [comment]
Now it works as planned. Thanks a lot for your work and support!

**Comment by shadow7412** [comment]
Happy to help - thanks for your concise replies :) It always helps when people respond with the information you need :P
