### ISSUE TITLE
Last update broke the driver, returns to home page after login

### ISSUE THREAD

**Issue by DNKROZ** [shadow7412/fronius-driver#2]
Hello.
First I want to thank you for your work, I really don't understand why these values are not exposed to modbus registry and the only way to change them is via web browser.

It seems that after upgrading to the last datalogger update the default behaviour has changed and it doesn't go to the /settings/evu page anymore, also, I got an error trying to login and didn't get pass the auth screen.

I solved the login error using a select object and selecting the option by value (Chat-GPT generated, sorry, selenium is completely out of my expertise :) ):
# Import Select class
from selenium.webdriver.support.ui import Select
# Create a Select object
select = Select(select_element)

# Select the option by value
select.select_by_value('string:service')

But I was still getting errors (no export data field located and so) after checking the actual loaded page I got the "default" (home page) instead of /settings/evu so I forced page loading and I added a delay to load the default page, forced the loading of the settings page (twice, don't ask why sometimes it got skipped) and a delay to load all values (to be able to locate the needed field):

 driver.implicitly_wait(10) #Wait main page to load
 driver.get(f"{args.fronius_url}/#/settings/evu") #Load settings page
 driver.get(f"{args.fronius_url}/#/settings/evu") #Load settings page ... again
 driver.implicitly_wait(12) #Wait settings page load and continue....
 
 This SEEMS to be functional but completely subpar, since I hace to wait, load the page, wait again... but I hope it gives some insight into what's happening right now with the last update, this is the data btw:

Software Version: 3.31.1-5

Best regards.

UPDATE: I didn't have time to reply or to replicate the issue and gather the data, but when trying to do so... now it works again ... so this can stay closed for the time being.

**Comment by shadow7412** [comment]
Interesting.

I'm not fully following exactly what's happening though - would you be able to attach the error messages and screenshots that the output of the command should be providing? This will help me get a much better idea of what's going on...

**Comment by shadow7412** [comment]
I'm going to close this, as you haven't replied in a while. If this is still an issue for you and you're able to provide the requested data, I'd be more than happy to look into it.
